version: "3.9"

services:
  maturita-app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://mahulina:heslo123@db:5432/mahulina_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LM_STUDIO_URL=https://kurim.ithope.eu/v1/chat/completions
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=mahulina
      - POSTGRES_PASSWORD=heslo123
      - POSTGRES_DB=mahulina_db