version: "3.9"

services:
  maturita-app:
    build: .
    container_name: maturita-app
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
    environment:
      - LM_STUDIO_URL=https://kurim.ithope.eu/v1/chat/completions
      - LM_STUDIO_TIMEOUT=60
      - OPENAI_API_KEY=sk-k_ILpNLyqBVD-6yqHXzvow